apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: dpu-network-operator-manager-role
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - '*'
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
