apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: dpu-network-operator-dpu-network-operator-daemon-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dpu-network-operator-dpu-network-operator-daemon
subjects:
- kind: ServiceAccount
  name: dpu-network-operator-dpu-network-operator-daemon
  namespace: openshift-dpu-network-operator
