# permissions for end users to view dpuclusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dpuclusterconfig-viewer-role
rules:
- apiGroups:
  - dpu.openshift.io
  resources:
  - dpuclusterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dpu.openshift.io
  resources:
  - dpuclusterconfigs/status
  verbs:
  - get
