# permissions for end users to edit dpuclusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dpuclusterconfig-editor-role
rules:
- apiGroups:
  - dpu.openshift.io
  resources:
  - dpuclusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dpu.openshift.io
  resources:
  - dpuclusterconfigs/status
  verbs:
  - get
